Fidev-io/framy

.github/workflows/acceptance_tests.yaml
.github/workflows/unit_tests.yaml
framy_generator/lib/framy_generator.dart
framy_generator/lib/generator/app_bar_generator.dart
framy_generator/lib/generator/fonts_page_generator.dart
framy_generator/lib/generator/framy_app_generator.dart
framy_generator/pubspec.lock
framy_generator/pubspec.yaml
framy_generator/test/generators/app_bar_generator_test.dart
framy_generator/test/generators/fonts_page_generator_test.dart
framy_generator/test/generators/framy_app_generator_test.dart
run_all_tests.sh
test_apps/counter_app/lib/main.app.framy.dart
test_apps/counter_app/test/fonts_page_test.dart
test_apps/counter_app/test/framy_app_test.dart
test_apps/counter_app/test_driver/fonts_page.dart
test_apps/counter_app/test_driver/fonts_page_test.dart
test_apps/counter_app/test_driver/github_firendly_ozzie.dart

Fonts page

---

framy_generator/lib/generator/fonts_page_generator.dart
framy_generator/lib/generator/main_generator.dart
framy_generator/test/generators/fonts_page_generator_test.dart
framy_generator/test/generators/main_generator_test.dart
run_all_tests.sh
test_apps/counter_app/lib/main.app.framy.dart
test_apps/counter_app/test/fonts_page_test.dart
test_apps/counter_app/test_driver/fonts_page_test.dart

Text style descriptions in font page

---

.github/workflows/acceptance_tests.yaml
run_all_tests.sh
test_apps/counter_app/test_driver/app_test.dart

Fixed CI automation tests setup

---

framy_generator/lib/framy_generator.dart
framy_generator/lib/generator/colors_page_generator.dart
framy_generator/lib/generator/drawer_generator.dart
framy_generator/lib/generator/framy_app_generator.dart
framy_generator/lib/generator/layout_template_generator.dart
framy_generator/lib/generator/routing_generator.dart
framy_generator/test/generators/colors_page_generator_test.dart
framy_generator/test/generators/drawer_generator_test.dart
framy_generator/test/generators/framy_app_generator_test.dart
framy_generator/test/generators/layout_template_generator_test.dart
framy_generator/test/generators/routing_generator_test.dart
test_apps/counter_app/lib/main.app.framy.dart
test_apps/counter_app/pubspec.yaml
test_apps/counter_app/test/colors_page_test.dart
test_apps/counter_app/test/framy_app_test.dart
test_apps/counter_app/test/layout_template_test.dart
test_apps/counter_app/test_driver/app_test.dart

Navigation

---

framy_generator/lib/generator/colors_page_generator.dart
framy_generator/test/generators/colors_page_generator_test.dart
test_apps/counter_app/lib/main.app.framy.dart
test_apps/counter_app/test/colors_page_test.dart
test_apps/counter_app/test_driver/app_test.dart

Added static color cards

---

framy_annotation/lib/src/framy_annotations.dart
framy_generator/build.yaml
framy_generator/lib/builder.dart
framy_generator/lib/framy_generator.dart
framy_generator/lib/framy_object.dart
framy_generator/lib/generator/framy_app_generator.dart
framy_generator/lib/generator/imports_generator.dart
framy_generator/lib/json_builder.dart
framy_generator/lib/theme_resolver.dart
framy_generator/pubspec.lock
framy_generator/pubspec.yaml
framy_generator/test/dummy_flutter_classes/color.dart
framy_generator/test/dummy_flutter_classes/theme_data.dart
framy_generator/test/generators/framy_app_generator_test.dart
framy_generator/test/generators/imports_generator_test.dart
framy_generator/test/resolvers/resolver_test.dart
test_apps/counter_app/lib/main.app.framy.dart
test_apps/counter_app/lib/main.dart
test_apps/counter_app/test/framy_app_test.dart
test_apps/counter_app/test_driver/app_test.dart

Added using custom theme

---

framy_generator/lib/framy_generator.dart
framy_generator/lib/framy_object.dart
framy_generator/lib/generator/colors_page_generator.dart
framy_generator/lib/theme_resolver.dart
framy_generator/test/generators/colors_page_generator_test.dart
framy_generator/test/resolvers/color.dart
framy_generator/test/resolvers/theme_resolver_test.dart

Added custom colors

---

framy_generator/lib/generator/colors_page_generator.dart
framy_generator/test/generators/colors_page_generator_test.dart
test_apps/counter_app/lib/main.app.framy.dart
test_apps/counter_app/test/colors_page_test.dart
test_apps/counter_app/test_driver/app_test.dart

Added Color Scheme colors

---

framy_generator/lib/framy_generator.dart
framy_generator/lib/generator/app_bar_page_generator.dart
framy_generator/lib/generator/button_page_generator.dart
framy_generator/lib/generator/drawer_generator.dart
framy_generator/lib/generator/routing_generator.dart
framy_generator/lib/generator/utils_generator.dart
framy_generator/test/generators/app_bar_page_generator_test.dart
framy_generator/test/generators/button_page_generator_test.dart
framy_generator/test/generators/drawer_generator_test.dart
framy_generator/test/generators/routing_generator_test.dart
test_apps/counter_app/lib/main.app.framy.dart
test_apps/counter_app/test/app_bar_page_test.dart
test_apps/counter_app/test/button_page_test.dart
test_apps/counter_app/test/drawer_test.dart
test_apps/counter_app/test/framy_app_test.dart
test_apps/counter_app/test/test_utils.dart
test_apps/counter_app/test_driver/app_test.dart

Material components AppBars and Buttons

---

framy_annotation/lib/src/framy_annotations.dart
framy_generator/build.yaml
framy_generator/lib/builder.dart
framy_generator/lib/framy_generator.dart
framy_generator/lib/framy_object.dart
framy_generator/lib/generator/drawer_generator.dart
framy_generator/lib/generator/routing_generator.dart
framy_generator/lib/generator/widget_page_generator.dart
framy_generator/lib/widget_resolver.dart
framy_generator/test/generators/drawer_generator_test.dart
framy_generator/test/generators/routing_generator_test.dart
framy_generator/test/generators/widget_page_generator_test.dart
framy_generator/test/resolvers/dummy_classes.dart
framy_generator/test/resolvers/theme_data.dart
framy_generator/test/resolvers/theme_resolver_test.dart
framy_generator/test/resolvers/widget_resolver_test.dart
run_all_tests.sh
test_apps/counter_app/lib/main.app.framy.dart
test_apps/counter_app/lib/main.dart
test_apps/counter_app/test/counter_fab_page_test.dart
test_apps/counter_app/test/drawer_test.dart
test_apps/counter_app/test/framy_app_test.dart
test_apps/counter_app/test_driver/app_test.dart

Simple widgets

---

framy_annotation/lib/src/framy_annotations.dart
framy_generator/build.yaml
framy_generator/lib/builder.dart
framy_generator/lib/framy_generator.dart
framy_generator/lib/framy_object.dart
framy_generator/lib/generator/dependency_model_generator.dart
framy_generator/lib/generator/widget_dependency_input_generator.dart
framy_generator/lib/generator/widget_page_generator.dart
framy_generator/lib/resolvers/model_resolver.dart
framy_generator/test/generators/widget_dependency_input_generator_test.dart
framy_generator/test/generators/widget_page_generator_test.dart
framy_generator/test/resolvers/widget_resolver_test.dart
test_apps/counter_app/lib/main.app.framy.dart
test_apps/counter_app/test/widget_dependencies_panel_test.dart
test_apps/counter_app/test/widget_dependency_input_test.dart
test_apps/weight_tracker/lib/main.app.framy.dart
test_apps/weight_tracker/lib/models/user.dart
test_apps/weight_tracker/test/widget_dependencies_panel_test.dart
test_apps/weight_tracker/test_driver/app_test.dart

Added support for widget class dependencies

---

framy_generator/example/pubspec.lock
framy_generator/lib/framy_generator.dart
framy_generator/lib/generator/widget_dependency_input_generator.dart
framy_generator/lib/generator/widget_dependency_null_switch_generator.dart
framy_generator/test/generators/widget_dependency_input_generator_test.dart
framy_generator/test/generators/widget_dependency_null_switch_generator_test.dart
framy_generator/test/generators/widget_dependency_null_switch_test.dart
test_apps/counter_app/lib/main.app.framy.dart
test_apps/counter_app/pubspec.lock
test_apps/weight_tracker/lib/main.app.framy.dart
test_apps/weight_tracker/pubspec.lock
test_apps/weight_tracker/test/widget_dependency_input_test.dart
test_apps/weight_tracker/test/widget_dependency_null_switch_test.dart
test_apps/weight_tracker/test_driver/app_test.dart

Setting dependency value to null

---

framy_generator/lib/framy_generator.dart
framy_generator/lib/generator/widget_dependency_input_generator.dart
framy_generator/lib/generator/widget_list_dependency_input_generator.dart
framy_generator/test/generators/widget_dependency_input_generator_test.dart
framy_generator/test/generators/widget_list_dependency_input_generator_test.dart
test_apps/counter_app/lib/main.app.framy.dart
test_apps/weight_tracker/lib/main.app.framy.dart
test_apps/weight_tracker/lib/models/user.dart
test_apps/weight_tracker/lib/pages/profile_page.dart
test_apps/weight_tracker/lib/widgets/user_emails_view.dart
test_apps/weight_tracker/test/widget_dependencies_panel_test.dart
test_apps/weight_tracker/test/widget_dependency_input_test.dart
test_apps/weight_tracker/test/widget_list_dependency_input_test.dart
test_apps/weight_tracker/test_driver/app_test.dart

Dependency lists

---

framy_annotation/lib/src/framy_annotations.dart
framy_generator/lib/framy_object.dart
framy_generator/lib/generator/imports_generator.dart
framy_generator/lib/generator/widget_page_generator.dart
framy_generator/lib/resolvers/model_resolver.dart
framy_generator/lib/resolvers/widget_resolver.dart
framy_generator/test/generators/imports_generator_test.dart
framy_generator/test/generators/model_constructor_map_generator_test.dart
framy_generator/test/generators/widget_page_generator_test.dart
framy_generator/test/resolvers/widget_resolver_test.dart
test_apps/weight_tracker/lib/home_page.dart
test_apps/weight_tracker/lib/main.app.framy.dart
test_apps/weight_tracker/lib/pages/profile_page.dart
test_apps/weight_tracker/pubspec.lock
test_apps/weight_tracker/pubspec.yaml
test_apps/weight_tracker/test/profile_page_custom_page_test.dart
test_apps/weight_tracker/test/widget_dependency_input_test.dart
test_apps/weight_tracker/test_driver/app_test.dart

Provider support

---

framy_generator/lib/framy_generator.dart
framy_generator/lib/framy_object.dart
framy_generator/lib/generator/enum_map_generator.dart
framy_generator/lib/generator/model_constructor_map_generator.dart
framy_generator/lib/generator/widget_dependency_input_generator.dart
framy_generator/lib/resolvers/model_resolver.dart
framy_generator/test/generators/enum_map_generator_test.dart
framy_generator/test/generators/model_constructor_map_generator_test.dart
framy_generator/test/generators/widget_dependency_input_generator_test.dart
framy_generator/test/resolvers/model_resolver_test.dart
test_apps/counter_app/lib/main.app.framy.dart
test_apps/weight_tracker/lib/main.app.framy.dart
test_apps/weight_tracker/lib/models/weight_unit.dart
test_apps/weight_tracker/lib/pages/profile_page.dart
test_apps/weight_tracker/lib/widgets/weight_unit_display.dart
test_apps/weight_tracker/test/widget_dependency_input_test.dart
test_apps/weight_tracker/test_driver/app_test.dart

Added support for enum dependencies

---

framy_generator/lib/framy_object.dart
framy_generator/lib/generator/dependency_model_generator.dart
framy_generator/lib/generator/model_constructor_map_generator.dart
framy_generator/lib/generator/widget_dependency_input_generator.dart
framy_generator/lib/generator/widget_dependency_null_switch_generator.dart
framy_generator/lib/generator/widget_page_generator.dart
framy_generator/lib/resolvers/model_resolver.dart
framy_generator/lib/resolvers/widget_resolver.dart
framy_generator/test/generators/imports_generator_test.dart
framy_generator/test/generators/model_constructor_map_generator_test.dart
framy_generator/test/generators/widget_dependency_input_generator_test.dart
framy_generator/test/generators/widget_dependency_null_switch_generator_test.dart
framy_generator/test/generators/widget_page_generator_test.dart
test_apps/counter_app/lib/main.app.framy.dart
test_apps/counter_app/test/counter_title_page_test.dart
test_apps/counter_app/test_driver/app_test.dart
test_apps/weight_tracker/lib/main.app.framy.dart
test_apps/weight_tracker/test/user_data_card_page_test.dart
test_apps/weight_tracker/test/widget_dependency_input_test.dart
test_apps/weight_tracker/test/widget_dependency_null_switch_test.dart
test_apps/weight_tracker/test_driver/app_test.dart

Null switch

---

framy_generator/lib/generator/widget_dependency_input_generator.dart
showcase/lib/main.dart
test_apps/counter_app/lib/main.app.framy.dart
test_apps/weight_tracker/lib/main.app.framy.dart

Improved UI for boolean type

---

framy_generator/CHANGELOG.md
framy_generator/lib/framy_generator.dart
framy_generator/lib/generator/datetime_dependency_input_generator.dart
framy_generator/lib/generator/widget_dependency_input_generator.dart
framy_generator/pubspec.yaml
framy_generator/test/generators/datetime_dependency_input_generator_test.dart
framy_generator/test/generators/widget_dependency_input_generator_test.dart
test_apps/counter_app/lib/main.app.framy.dart
test_apps/counter_app/pubspec.lock
test_apps/weight_tracker/lib/main.app.framy.dart
test_apps/weight_tracker/lib/models/weight_entry.dart
test_apps/weight_tracker/lib/widgets/weight_entry_list_item.dart
test_apps/weight_tracker/pubspec.lock
test_apps/weight_tracker/pubspec.yaml
test_apps/weight_tracker/test/widget_dependency_input_test.dart
test_apps/weight_tracker/test_driver/app_test.dart

Datetime support

---

framy_annotation/example/pubspec.lock
framy_generator/example/pubspec.lock
framy_generator/lib/framy_generator.dart
framy_generator/lib/generator/button_page_generator.dart
framy_generator/lib/generator/drawer_generator.dart
framy_generator/lib/generator/routing_generator.dart
framy_generator/lib/generator/toggle_page_generator.dart
framy_generator/test/generators/button_page_generator_test.dart
framy_generator/test/generators/drawer_generator_test.dart
framy_generator/test/generators/routing_generator_test.dart
framy_generator/test/generators/toggle_page_generator_test.dart
test_apps/counter_app/lib/main.app.framy.dart
test_apps/counter_app/pubspec.lock
test_apps/counter_app/test/button_page_test.dart
test_apps/counter_app/test/drawer_test.dart
test_apps/counter_app/test/toggle_page_test.dart
test_apps/counter_app/test_driver/app_test.dart
test_apps/weight_tracker/lib/main.app.framy.dart
test_apps/weight_tracker/pubspec.lock

Material components (toggle, dropdown)

---

framy_generator/example/pubspec.lock
framy_generator/lib/framy_generator.dart
framy_generator/lib/generator/widget_cutom_page_template_generator.dart
framy_generator/lib/generator/widget_page_generator.dart
framy_generator/test/generators/widget_cutom_page_template_generator_test.dart
framy_generator/test/generators/widget_page_generator_test.dart
test_apps/counter_app/lib/main.app.framy.dart
test_apps/counter_app/pubspec.lock
test_apps/weight_tracker/lib/main.app.framy.dart
test_apps/weight_tracker/pubspec.lock

Removed boilerplate generation for custom pages

---

framy_annotation/example/pubspec.yaml
framy_generator/CHANGELOG.md
framy_generator/example/pubspec.yaml
framy_generator/lib/framy_generator.dart
framy_generator/lib/generator/imports_generator.dart
framy_generator/lib/generator/widget_cutom_page_template_generator.dart
framy_generator/pubspec.yaml
framy_generator/test/generators/widget_cutom_page_template_generator_test.dart
test_apps/counter_app/lib/main.app.framy.dart
test_apps/counter_app/lib/main.dart
test_apps/counter_app/pubspec.lock
test_apps/counter_app/pubspec.yaml
test_apps/counter_app/test/counter_title_page_test.dart
test_apps/counter_app/test_driver/app_test.dart
test_apps/weight_tracker/lib/main.app.framy.dart
test_apps/weight_tracker/lib/main.dart
test_apps/weight_tracker/pubspec.lock
test_apps/weight_tracker/pubspec.yaml

Added support for DevicePreview

---

framy_generator/CHANGELOG.md
framy_generator/lib/generator/widget_cutom_page_template_generator.dart
framy_generator/pubspec.yaml
framy_generator/test/generators/widget_cutom_page_template_generator_test.dart
test_apps/counter_app/ios/Flutter/Debug.xcconfig
test_apps/counter_app/ios/Flutter/Release.xcconfig
test_apps/counter_app/ios/Runner.xcodeproj/project.pbxproj
test_apps/counter_app/ios/Runner.xcworkspace/contents.xcworkspacedata
test_apps/counter_app/lib/main.app.framy.dart
test_apps/counter_app/macos/Flutter/Flutter-Debug.xcconfig
test_apps/counter_app/macos/Flutter/Flutter-Release.xcconfig
test_apps/counter_app/macos/Flutter/GeneratedPluginRegistrant.swift
test_apps/counter_app/macos/Runner.xcodeproj/project.pbxproj
test_apps/counter_app/macos/Runner.xcworkspace/contents.xcworkspacedata
test_apps/counter_app/pubspec.lock
test_apps/weight_tracker/ios/Flutter/Debug.xcconfig
test_apps/weight_tracker/ios/Flutter/Release.xcconfig
test_apps/weight_tracker/ios/Runner.xcodeproj/project.pbxproj
test_apps/weight_tracker/ios/Runner.xcworkspace/contents.xcworkspacedata
test_apps/weight_tracker/lib/main.app.framy.dart
test_apps/weight_tracker/macos/Flutter/Flutter-Debug.xcconfig
test_apps/weight_tracker/macos/Flutter/Flutter-Release.xcconfig
test_apps/weight_tracker/macos/Flutter/GeneratedPluginRegistrant.swift
test_apps/weight_tracker/macos/Runner.xcodeproj/project.pbxproj
test_apps/weight_tracker/macos/Runner.xcworkspace/contents.xcworkspacedata
test_apps/weight_tracker/pubspec.lock

Fixed state lose on hot reload #96

---

framy_generator/CHANGELOG.md
framy_generator/lib/generator/framy_app_generator.dart
framy_generator/test/generators/framy_app_generator_test.dart
framy_generator/test/resolvers/theme_resolver_test.dart
test_apps/weight_tracker/lib/app_theme.dart

Fixed generating theme when multiple theme framy objects passed

---

framy_generator/CHANGELOG.md
framy_generator/lib/generator/dependency_model_generator.dart
framy_generator/lib/generator/widget_list_dependency_input_generator.dart
framy_generator/test/generators/dependency_model_generator_test.dart
framy_generator/test/generators/widget_list_dependency_input_generator_test.dart
test_apps/counter_app/lib/main.app.framy.dart
test_apps/counter_app/test/widget_dependencies_panel_test.dart
test_apps/weight_tracker/lib/main.app.framy.dart
test_apps/weight_tracker/test/dependency_model_test.dart
test_apps/weight_tracker/test/framy_model_constructor_map_test.dart
test_apps/weight_tracker/test/preset_dropdown_test.dart
test_apps/weight_tracker/test/user_data_card_page_test.dart
test_apps/weight_tracker/test/widget_list_dependency_input_test.dart
test_apps/weight_tracker/test_driver/app_test.dart

Changed to default to custom objects instead of nulls

---

framy_generator/CHANGELOG.md
framy_generator/lib/framy_object.dart
framy_generator/lib/generator/imports_generator.dart
framy_generator/test/generators/imports_generator_test.dart
framy_generator/test/resolvers/model_resolver_test.dart
framy_generator/test/resolvers/preset_resolver_test.dart
framy_generator/test/resolvers/theme_resolver_test.dart
framy_generator/test/resolvers/widget_resolver_test.dart
test_apps/counter_app/lib/main.app.framy.dart
test_apps/weight_tracker/lib/main.app.framy.dart
test_apps/weight_tracker/lib/models/dummy_test_widget_model.dart
test_apps/weight_tracker/lib/widgets/dummy_test_widget.dart
test_apps/weight_tracker/test/dummy_test_widget_page_test.dart
test_apps/weight_tracker/test_driver/app_test.dart

Model imports fix

---

framy_generator/CHANGELOG.md
framy_generator/lib/generator/constructor_dropdown_generator.dart
framy_generator/lib/generator/dependency_model_generator.dart
framy_generator/lib/generator/utils.dart
framy_generator/lib/generator/widget_list_dependency_input_generator.dart
framy_generator/test/generators/constructor_dropdown_generator_test.dart
framy_generator/test/generators/dependency_model_generator_test.dart
framy_generator/test/generators/subdependecies_map_generator_test.dart
framy_generator/test/generators/widget_page_generator_test.dart
test_apps/counter_app/lib/main.app.framy.dart
test_apps/counter_app/test/widget_dependencies_panel_test.dart
test_apps/counter_app/test/widget_dependency_input_test.dart
test_apps/weight_tracker/lib/main.app.framy.dart
test_apps/weight_tracker/lib/models/statistics_page_state.dart
test_apps/weight_tracker/lib/models/statistics_page_state.freezed.dart
test_apps/weight_tracker/lib/pages/statistics_page.dart
test_apps/weight_tracker/pubspec.lock
test_apps/weight_tracker/pubspec.yaml
test_apps/weight_tracker/test/constructor_dropdown_test.dart
test_apps/weight_tracker/test/dependency_model_test.dart
test_apps/weight_tracker/test/framy_model_constructor_map_test.dart
test_apps/weight_tracker/test/preset_dropdown_test.dart
test_apps/weight_tracker/test/statistics_page_custom_page_test.dart
test_apps/weight_tracker/test/widget_dependencies_panel_test.dart
test_apps/weight_tracker/test/widget_dependency_input_test.dart
test_apps/weight_tracker/test/widget_list_dependency_input_test.dart
test_apps/weight_tracker/test_driver/app_test.dart

From now changing constructors also causes value to rebuild.
Resolves #67

Added default subDependencies and constructor values for freezed support

---

framy_annotation/CHANGELOG.md
framy_annotation/lib/src/framy_annotations.dart
framy_annotation/pubspec.yaml
framy_generator/CHANGELOG.md
framy_generator/build.yaml
framy_generator/example/pubspec.yaml
framy_generator/lib/builder.dart
framy_generator/lib/framy_generator.dart
framy_generator/lib/framy_object.dart
framy_generator/lib/generator/imports_generator.dart
framy_generator/lib/generator/main_generator.dart
framy_generator/lib/generator/widget_page_generator.dart
framy_generator/lib/resolvers/register_riverpod_resolver.dart
framy_generator/lib/resolvers/widget_resolver.dart
framy_generator/pubspec.yaml
framy_generator/test/generators/imports_generator_test.dart
framy_generator/test/generators/main_generator_test.dart
framy_generator/test/generators/widget_page_generator_test.dart
framy_generator/test/resolvers/dummy_classes.dart
framy_generator/test/resolvers/register_riverpod_resolver_test.dart
framy_generator/test/resolvers/widget_resolver_test.dart
test_apps/counter_app/pubspec.lock
test_apps/weight_tracker/lib/home_page.dart
test_apps/weight_tracker/lib/main.app.framy.dart
test_apps/weight_tracker/lib/main.dart
test_apps/weight_tracker/lib/pages/history_page.dart
test_apps/weight_tracker/lib/widgets/weight_entry_list_item.dart
test_apps/weight_tracker/pubspec.lock
test_apps/weight_tracker/pubspec.yaml
test_apps/weight_tracker/test/history_page_custom_page_test.dart

Added riverpod support

---

framy_generator/CHANGELOG.md
framy_generator/lib/framy_object.dart
framy_generator/lib/generator/model_constructor_map_generator.dart
framy_generator/lib/resolvers/model_resolver.dart
framy_generator/pubspec.yaml
framy_generator/test/generators/model_constructor_map_generator_test.dart
framy_generator/test/resolvers/dummy_classes.dart
framy_generator/test/resolvers/model_resolver_test.dart
test_apps/counter_app/pubspec.lock
test_apps/weight_tracker/lib/main.app.framy.dart
test_apps/weight_tracker/lib/models/built_value_user.dart
test_apps/weight_tracker/lib/models/built_value_user.g.dart
test_apps/weight_tracker/lib/widgets/built_value_example_widget.dart
test_apps/weight_tracker/pubspec.lock
test_apps/weight_tracker/pubspec.yaml
test_apps/weight_tracker/test/built_value_example_widget_custom_page_test.dart
test_apps/weight_tracker/test_driver/app_test.dart

Added BuiltValue support

---

framy_generator/CHANGELOG.md
framy_generator/lib/generator/app_bar_generator.dart
framy_generator/lib/generator/framy_app_generator.dart
framy_generator/lib/generator/layout_template_generator.dart
framy_generator/test/generators/app_bar_generator_test.dart
framy_generator/test/generators/drawer_generator_test.dart
framy_generator/test/generators/layout_template_generator_test.dart
test_apps/counter_app/lib/main.app.framy.dart
test_apps/counter_app/test/layout_template_test.dart
test_apps/counter_app/test/test_utils.dart
test_apps/counter_app/test_driver/app_test.dart
test_apps/weight_tracker/lib/main.app.framy.dart
test_apps/weight_tracker/test/test_utils.dart

Hiding nav menu

---

framy_annotation/lib/src/framy_annotations.dart
framy_generator/CHANGELOG.md
framy_generator/lib/framy_generator.dart
framy_generator/lib/generator/storyboard_generator.dart
framy_generator/lib/generator/widget_cutom_page_template_generator.dart
framy_generator/test/generators/storyboard_page_generator_test.dart
test_apps/counter_app/lib/main.app.framy.dart
test_apps/counter_app/pubspec.lock
test_apps/counter_app/pubspec.yaml
test_apps/weight_tracker/lib/main.app.framy.dart
test_apps/weight_tracker/pubspec.lock
test_apps/weight_tracker/pubspec.yaml
test_apps/weight_tracker/test_driver/app_test.dart

Added device preview to storyboard

---

framy_generator/CHANGELOG.md
framy_generator/lib/framy_generator.dart
framy_generator/lib/generator/lint_ignores_generator.dart
test_apps/counter_app/lib/main.app.framy.dart
test_apps/weight_tracker/lib/main.app.framy.dart
test_apps/weight_tracker/lib/models/statistics_page_state.freezed.dart

Add lint ignores

---

framy_generator/CHANGELOG.md
framy_generator/lib/generator/widget_cutom_page_template_generator.dart
framy_generator/pubspec.yaml
framy_generator/test/generators/widget_cutom_page_template_generator_test.dart
test_apps/counter_app/lib/main.app.framy.dart
test_apps/counter_app/pubspec.lock
test_apps/counter_app/test/counter_fab_page_test.dart
test_apps/counter_app/test/counter_title_page_test.dart
test_apps/counter_app/test_driver/app_test.dart
test_apps/weight_tracker/lib/main.app.framy.dart
test_apps/weight_tracker/pubspec.lock
test_apps/weight_tracker/test/built_value_example_widget_custom_page_test.dart

Resolves #70 
It doesn't preserve state across devices but I think that for now, it's enough.

Resizing dependencies panel

---

framy_generator/CHANGELOG.md
framy_generator/lib/config/framy_config.dart
framy_generator/lib/config/yaml_config_loader.dart
framy_generator/lib/framy_generator.dart
framy_generator/lib/generator/framy_app_generator.dart
framy_generator/pubspec.yaml
framy_generator/test/generators/framy_app_generator_test.dart
test_apps/counter_app/lib/main.app.framy.dart
test_apps/counter_app/pubspec.lock
test_apps/counter_app/pubspec.yaml
test_apps/counter_app/test/framy_app_test.dart
test_apps/counter_app/test_driver/app_test.dart
test_apps/weight_tracker/framy.yaml
test_apps/weight_tracker/lib/main.app.framy.dart
test_apps/weight_tracker/pubspec.lock
test_apps/weight_tracker/test_driver/app_test.dart

Resolves #13 
Current default options:
```yaml
framy:
wrap-with-center: false
wrap-with-safearea: false
wrap-with-scaffold: true
wrap-with-devicepreview: true
show-material-components: true
show-storyboard: true
```

Added yaml config options

---

README.md
framy_generator/README.md

Fixed links to example apps in README
